Repository KREAMIFY/KREAMIFY_BE, pull requests merged in 2025-04, with the labels that each got.

#63 #59 [Feat] 판매 입찰 취소 기능 구현
  src/main/java/com/kreamify/domain/deal/repository/SellingRepository.java
  src/main/java/com/kreamify/domain/deal/service/SellingService.java
  src/main/java/com/kreamify/domain/user/controller/UserShoppingInfoController.java
  src/test/java/com/kreamify/domain/user/controller/UserControllerTest.java
Labels: Backend, ✨ Feat

#65 #64 [Feat] 상품 조회 기능 개선
  src/main/java/com/kreamify/domain/product/controller/AdminController.java
  src/main/java/com/kreamify/domain/product/controller/ProductController.java
  src/main/java/com/kreamify/domain/product/repository/ProductRepository.java
  src/main/java/com/kreamify/domain/product/repository/ProductSpecification.java
  src/main/java/com/kreamify/domain/product/service/ProductService.java
Labels: Backend, ✨ Feat

#69 #66 [Fix] 구매 관련 기능 API 리펙토링
  src/main/java/com/kreamify/domain/deal/domain/BuyingBid.java
  src/main/java/com/kreamify/domain/deal/dto/BuyingBidResponse.java
Labels: 🐛 Fix

#68 #67 [Fix] 판매입찰 등록 시 입찰 취소 상태 변경 오류 해결
  src/main/java/com/kreamify/domain/deal/controller/SellingController.java
  src/main/java/com/kreamify/domain/deal/model/DealStatus.java
  src/main/java/com/kreamify/domain/deal/repository/SellingRepository.java
  src/main/java/com/kreamify/domain/deal/service/SellingService.java
Labels: 🐛 Fix

#72 #70 [Test] 판매 통합테스트
  src/main/java/com/kreamify/domain/deal/controller/SellingController.java
  src/main/java/com/kreamify/domain/deal/dto/SellingBidResponse.java
  src/test/java/com/kreamify/domain/deal/controller/SellingControllerTest.java
  src/test/java/com/kreamify/domain/deal/dto/BidTestRequest.java
  src/test/java/com/kreamify/domain/deal/dto/BuyTestRequest.java
  src/test/java/com/kreamify/domain/user/controller/UserSellInfoControllerTest.java
Labels: 💻 Testing

#73 #71 [test] 구매 통합 테스트
  src/test/java/com/kreamify/domain/deal/controller/BuyingControllerTest.java
  src/test/java/com/kreamify/domain/user/controller/UserBuyInfoControllerTest.java
Labels: 💻 Testing

#76 #74 [Refactor] 구매 입찰 등록, 변경 로직 리팩토링
  src/main/java/com/kreamify/domain/deal/repository/BuyingRepository.java
  src/main/java/com/kreamify/domain/deal/service/BuyingService.java
Labels: 🐛 Fix
