Repository KREAMIFY/KREAMIFY_BE, pull requests merged in 2025-03, with the labels that each got.

#38 #35 [Test] 사용자 회원가입 기능 테스트
  src/main/java/com/kreamify/domain/user/domain/User.java
  src/main/java/com/kreamify/domain/user/service/UserService.java
  src/main/java/com/kreamify/global/error/GlobalExceptionHandler.java
  src/main/resources/application.properties
  src/test/java/com/kreamify/domain/config/TestConfig.java
  src/test/java/com/kreamify/domain/user/controller/UserControllerTest.java
  src/test/java/com/kreamify/domain/user/dto/UserSignUpTestRequest.java
Labels: Backend, ✨ Feat, 💻 Testing, 🐛 Fix

#43 #41 [Test] 사용자 수정 및 탈퇴 테스트
  build.gradle
  src/main/java/com/kreamify/domain/user/dto/UserResponse.java
  src/test/java/com/kreamify/domain/user/controller/UserControllerTest.java
  src/test/java/com/kreamify/domain/user/dto/UserSignUpTestRequest.java
  src/test/java/com/kreamify/domain/user/dto/UserUpdateTestRequest.java
Labels: 💻 Testing, 🐛 Fix

#42 #40 [Feat] 판매 입찰 등록 기능 구현
  src/main/java/com/kreamify/domain/deal/controller/BuyingController.java
  src/main/java/com/kreamify/domain/deal/controller/SellingController.java
  src/main/java/com/kreamify/domain/deal/domain/SellingBid.java
  src/main/java/com/kreamify/domain/deal/exception/NotFoundBidException.java
  src/main/java/com/kreamify/domain/deal/repository/SellingRepository.java
  src/main/java/com/kreamify/domain/deal/service/BuyingService.java
  src/main/java/com/kreamify/domain/deal/service/SellingService.java
  src/main/java/com/kreamify/domain/product/domain/ProductOption.java
Labels: Backend, ✨ Feat

#46 #44 [Feat] 즉시 구매 기능 구현
  src/main/java/com/kreamify/domain/deal/controller/BuyingController.java
  src/main/java/com/kreamify/domain/deal/domain/Deal.java
  src/main/java/com/kreamify/domain/deal/domain/SellingBid.java
  src/main/java/com/kreamify/domain/deal/dto/BuyRequest.java
  src/main/java/com/kreamify/domain/deal/dto/DealResponse.java
  src/main/java/com/kreamify/domain/deal/model/DealStatus.java
  src/main/java/com/kreamify/domain/deal/repository/SellingRepository.java
  src/main/java/com/kreamify/domain/deal/service/BuyingService.java
  src/main/java/com/kreamify/domain/deal/service/DealService.java
  src/main/java/com/kreamify/domain/deal/service/SellingService.java
  src/main/java/com/kreamify/domain/user/controller/UserController.java
  src/main/java/com/kreamify/global/error/GlobalExceptionHandler.java
Labels: Backend, ✨ Feat

#47 #45 [Feat] 즉시 판매 기능 구현
  src/main/java/com/kreamify/domain/deal/controller/SellingController.java
  src/main/java/com/kreamify/domain/deal/domain/BuyingBid.java
  src/main/java/com/kreamify/domain/deal/repository/BuyingRepository.java
  src/main/java/com/kreamify/domain/deal/service/BuyingService.java
  src/main/java/com/kreamify/domain/deal/service/DealService.java
  src/main/java/com/kreamify/domain/deal/service/SellingService.java
  src/main/java/com/kreamify/domain/product/domain/ProductOption.java
Labels: Backend, ✨ Feat

#49 #48 [Docs] README.md 수정
  README.md
Labels: 📄 Docs

#54 #53 [Fix] 서비스 간 순환 참조 문제 해결
  src/main/java/com/kreamify/domain/deal/service/BuyingService.java
  src/main/java/com/kreamify/domain/deal/service/SellingService.java
Labels: 🚨 Error, 🐛 Fix

#55 #52 [Feat] 구매 내역 조회 기능 구현
  src/main/java/com/kreamify/domain/deal/domain/BuyingBid.java
  src/main/java/com/kreamify/domain/deal/domain/Deal.java
  src/main/java/com/kreamify/domain/deal/dto/BuyingBidResponse.java
  src/main/java/com/kreamify/domain/deal/dto/DealHistoryResponse.java
  src/main/java/com/kreamify/domain/deal/repository/BuyingRepository.java
  src/main/java/com/kreamify/domain/deal/repository/DealRepository.java
  src/main/java/com/kreamify/domain/deal/service/BuyingService.java
  src/main/java/com/kreamify/domain/deal/service/DealService.java
  src/main/java/com/kreamify/domain/user/controller/UserShoppingInfoController.java
Labels: Backend, ✨ Feat

#60 #51 [Feat] 회원 판매내역 조회기능 구현 및 코드 리팩터링
  src/main/java/com/kreamify/domain/deal/domain/Deal.java
  src/main/java/com/kreamify/domain/deal/domain/SellingBid.java
  src/main/java/com/kreamify/domain/deal/dto/BuyingHistoryResponse.java
  src/main/java/com/kreamify/domain/deal/dto/DealHistoryResponse.java
  src/main/java/com/kreamify/domain/deal/dto/SellingBidResponse.java
  src/main/java/com/kreamify/domain/deal/dto/SellingHistoryResponse.java
  src/main/java/com/kreamify/domain/deal/model/DealStatus.java
  src/main/java/com/kreamify/domain/deal/repository/BuyingRepository.java
  src/main/java/com/kreamify/domain/deal/repository/DealRepository.java
  src/main/java/com/kreamify/domain/deal/repository/SellingRepository.java
  src/main/java/com/kreamify/domain/deal/service/BuyingService.java
  src/main/java/com/kreamify/domain/deal/service/DealService.java
  src/main/java/com/kreamify/domain/deal/service/SellingService.java
  src/main/java/com/kreamify/domain/user/controller/UserController.java
  src/main/java/com/kreamify/domain/user/controller/UserShoppingInfoController.java
  src/main/java/com/kreamify/domain/user/domain/User.java
  src/main/java/com/kreamify/domain/user/dto/UserBuyingDealHistoryResponse.java
  src/main/java/com/kreamify/domain/user/dto/UserDealHistoryResponse.java
  src/main/java/com/kreamify/domain/user/dto/UserDealResponse.java
  src/main/java/com/kreamify/domain/user/service/UserService.java
Labels: Backend, ✨ Feat

#58 #57 [Feat] 구매 입찰 취소 기능 구현
  src/main/java/com/kreamify/domain/deal/domain/BuyingBid.java
  src/main/java/com/kreamify/domain/deal/model/DealStatus.java
  src/main/java/com/kreamify/domain/deal/service/BuyingService.java
  src/main/java/com/kreamify/domain/user/controller/UserShoppingInfoController.java
  src/main/java/com/kreamify/domain/user/service/UserService.java
Labels: Backend, ✨ Feat
